services:
  - type: web
    name: task-manager-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        fromSecret: MONGODB_URI
      - key: JWT_SECRET
        fromSecret: JWT_SECRET
      - key: JWT_EXPIRE
        value: 7d
      - key: PORT
        value: 5000